language: python
python:
  - "3.6"

# command to install dependencies
install: 
  - python setup.py develop
  - pip install coveralls flake8 mock

# command to run tests
script:
  - flake8 tinkerer tinkertest
  - nosetests --with-coverage --cover-package=tinkerer

# after test run
after_success:
  - coveralls
